'use strict';

function encode(stitches, options = {}) {
  const { name = 'design', colors = ['#000000'], scale = 0.1 } = options;

  // Find bounds
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  for (const s of stitches) {
    if (s.type === 'end') continue;
    minX = Math.min(minX, s.x);
    minY = Math.min(minY, s.y);
    maxX = Math.max(maxX, s.x);
    maxY = Math.max(maxY, s.y);
  }
  if (!isFinite(minX)) { minX = 0; minY = 0; maxX = 1000; maxY = 1000; }

  const pad = 20;
  const vw = (maxX - minX) * scale + pad * 2;
  const vh = (maxY - minY) * scale + pad * 2;

  // Build path segments (break on jump/trim/end)
  const segments = [];
  let currentSegment = [];
  let colorIdx = 0;

  for (const s of stitches) {
    if (s.type === 'end') {
      if (currentSegment.length > 1) segments.push({ points: currentSegment, color: colors[colorIdx] || '#000000' });
      currentSegment = [];
      break;
    }
    if (s.type === 'jump' || s.type === 'trim') {
      if (currentSegment.length > 1) segments.push({ points: currentSegment, color: colors[colorIdx] || '#000000' });
      currentSegment = [s];
    } else if (s.type === 'color_change') {
      if (currentSegment.length > 1) segments.push({ points: currentSegment, color: colors[colorIdx] || '#000000' });
      currentSegment = [];
      colorIdx = (colorIdx + 1) % colors.length;
    } else {
      currentSegment.push(s);
    }
  }
  if (currentSegment.length > 1) segments.push({ points: currentSegment, color: colors[colorIdx] || '#000000' });

  const paths = segments.map(({ points, color }) => {
    const d = points.map((p, i) => {
      const x = ((p.x - minX) * scale + pad).toFixed(2);
      const y = ((p.y - minY) * scale + pad).toFixed(2);
      return i === 0 ? `M${x},${y}` : `L${x},${y}`;
    }).join(' ');
    return `  <path d="${d}" fill="none" stroke="${color}" stroke-width="0.5" stroke-linecap="round" stroke-linejoin="round"/>`;
  });

  const stitchCount = stitches.filter(s => s.type === 'stitch').length;

  return [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${vw.toFixed(2)} ${vh.toFixed(2)}" width="${vw.toFixed(2)}mm" height="${vh.toFixed(2)}mm">`,
    `  <title>${name}</title>`,
    `  <desc>Stitches: ${stitchCount} | Generated by Wavstat Digitizer</desc>`,
    `  <rect width="100%" height="100%" fill="white"/>`,
    ...paths,
    `</svg>`,
  ].join('\n');
}

module.exports = { encode };
